debug: false

spring:
  application:
    name: cm-business
  profiles:
    active: dev
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql


mybatis:
  configuration:
    mapUnderscoreToCamelCase: true


eureka:
  instance:
    prefer-ip-address: true


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    httptrace:
      enabled: true
  info:
    encoding: utf8
    build:
      enabled: true
