debug: false

spring:
  application:
    name: cm-business
  profiles:
    active: dev
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

mybatis:
  configuration:
    mapUnderscoreToCamelCase: true